import type { ScraperProvider, ScrapedProduct, Platform } from "./types";

/**
 * ScraperAPI Provider
 * Primary provider for AliExpress, fallback for Amazon
 * https://www.scraperapi.com/
 */
export class ScraperAPIProvider implements ScraperProvider {
  name = "scraperapi";
  supportedPlatforms: Platform[] = ["aliexpress", "amazon"];
  private apiKey: string;

  constructor(apiKey: string) {
    this.apiKey = apiKey;
  }

  async scrapeProduct(url: string): Promise<ScrapedProduct> {
    const platform = this.detectPlatform(url);
    if (!platform) {
      throw new Error("Unsupported URL format");
    }

    // ScraperAPI endpoint
    const apiUrl = new URL("https://api.scraperapi.com/");
    apiUrl.searchParams.set("api_key", this.apiKey);
    apiUrl.searchParams.set("url", url);
    apiUrl.searchParams.set("render", "true"); // Enable JavaScript rendering

    const response = await fetch(apiUrl.toString());

    if (!response.ok) {
      throw new Error(`ScraperAPI error: ${response.status}`);
    }

    const html = await response.text();

    // Parse based on platform
    if (platform === "aliexpress") {
      return this.parseAliExpress(html, url);
    } else {
      return this.parseAmazon(html, url);
    }
  }

  private detectPlatform(url: string): Platform | null {
    if (url.includes("aliexpress.")) return "aliexpress";
    if (url.includes("amazon.")) return "amazon";
    return null;
  }

  private parseAliExpress(html: string, sourceUrl: string): ScrapedProduct {
    // TODO: Implement proper HTML parsing
    // For POC, we'll use basic regex patterns
    // In production, use a proper parser like cheerio

    const titleMatch = html.match(/<title[^>]*>([^<]+)</i);
    const title = titleMatch?.[1]?.replace(/ - AliExpress.*/, "").trim() || "منتج من AliExpress";

    // Extract images from JSON data embedded in page
    const imageMatches = html.match(/"imageUrl"\s*:\s*"([^"]+)"/g) || [];
    const images = imageMatches
      .map(m => m.match(/"imageUrl"\s*:\s*"([^"]+)"/)?.[1])
      .filter((url): url is string => !!url && url.startsWith("http"))
      .slice(0, 10);

    // Extract price
    const priceMatch = html.match(/"formattedActivityPrice"\s*:\s*"([^"]+)"/);
    const priceStr = priceMatch?.[1] || "0";
    const price = parseFloat(priceStr.replace(/[^0-9.]/g, "")) || 0;

    return {
      title,
      description: "", // Will be extracted or generated by AI
      price,
      currency: "USD",
      images: images.length > 0 ? images : ["https://placehold.co/400x400/e2e8f0/64748b?text=No+Image"],
      sourceUrl,
      platform: "aliexpress",
    };
  }

  private parseAmazon(html: string, sourceUrl: string): ScrapedProduct {
    // TODO: Implement proper HTML parsing
    const titleMatch = html.match(/<span[^>]*id="productTitle"[^>]*>([^<]+)</i);
    const title = titleMatch?.[1]?.trim() || "منتج من Amazon";

    // Extract images
    const imageMatches = html.match(/"large"\s*:\s*"([^"]+)"/g) || [];
    const images = imageMatches
      .map(m => m.match(/"large"\s*:\s*"([^"]+)"/)?.[1])
      .filter((url): url is string => !!url && url.startsWith("http"))
      .slice(0, 10);

    // Extract price
    const priceMatch = html.match(/<span[^>]*class="[^"]*a-price-whole[^"]*"[^>]*>([^<]+)/i);
    const priceStr = priceMatch?.[1] || "0";
    const price = parseFloat(priceStr.replace(/[^0-9.]/g, "")) || 0;

    return {
      title,
      description: "",
      price,
      currency: "USD",
      images: images.length > 0 ? images : ["https://placehold.co/400x400/e2e8f0/64748b?text=No+Image"],
      sourceUrl,
      platform: "amazon",
    };
  }
}
